server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
      #defaultZone: http://discovery:8761/eureka/
  healthcheck:
    enable: true
  instance:
    hostname: ribbon
    preferIpAddress: false
    health-check-url: http://movie:8010/info  # 健康检查的URL
    lease-renewal-interval-in-seconds: 10   # 续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 30  # 续约到期时间（默认90秒）