server:
  port: 8020
spring:
  application:
    name: microservice-consumer-movie-feign
eureka:
  client:
    serviceUrl:
    defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
      #defaultZone: http://discovery:8761/eureka/
  healthcheck:
    enable: true
  instance:
    hostname: feign
    preferIpAddress: false  #preferIpAddress设为false或者不设置，否则将会造成在单个主机上测试，Turbine只显示一个图表的情况
    health-check-url: http://movie:8020/info  # 健康检查的URL
    lease-renewal-interval-in-seconds: 10   # 续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 30  # 续约到期时间（默认90秒）
ribbon:
  eureka:
    enabled: true
    # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，
    # 而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。
    # 参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbonwithout-eureka
    ### 参考：https://spring.io/guides/gs/client-side-load-balancing/