server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuanbp/spring-cloud-microservice-study/
          # 配置git仓库的地址
          search-paths: config-repo
          # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: yuanbp0912@163.com
          # git仓库的账号
          password: 19930912yuan
          # git仓库的密码